spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: products-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1